var month_data = [
    {
        month_index: 11,
        amount_of_days: 31,
        starting_day: 5,
        year: 2017
    }, {
        month_index: 0,
        amount_of_days: 31,
        starting_day: 1,
        year: 2018
    }, {
        month_index: 1,
        amount_of_days: 28,
        starting_day: 4,
        year: 2018
    }, {
        month_index: 2,
        amount_of_days: 31,
        starting_day: 4,
        year: 2018
    }, {
        month_index: 3,
        amount_of_days: 30,
        starting_day: 0,
        year: 2018
    }, {
        month_index: 4,
        amount_of_days: 31,
        starting_day: 2,
        year: 2018
    }, {
        month_index: 5,
        amount_of_days: 30,
        starting_day: 5,
        year: 2018
    }, {
        month_index: 6,
        amount_of_days: 31,
        starting_day: 0,
        year: 2018
    }, {
        month_index: 7,
        amount_of_days: 31,
        starting_day: 3,
        year: 2018
    }, {
        month_index: 8,
        amount_of_days: 30,
        starting_day: 6,
        year: 2018
    }, {
        month_index: 9,
        amount_of_days: 31,
        starting_day: 1,
        year: 2018
    }, {
        month_index: 10,
        amount_of_days: 30,
        starting_day: 4,
        year: 2018
    }, {
        month_index: 11,
        amount_of_days: 31,
        starting_day: 6,
        year: 2018
    }, {
        month_index: 0,
        amount_of_days: 31,
        starting_day: 2,
        year: 2019
    }, {
        month_index: 1,
        amount_of_days: 28,
        starting_day: 5,
        year: 2019
    }, {
        month_index: 2,
        amount_of_days: 31,
        starting_day: 5,
        year: 2019
    }, {
        month_index: 3,
        amount_of_days: 30,
        starting_day: 1,
        year: 2019
    }, {
        month_index: 4,
        amount_of_days: 31,
        starting_day: 3,
        year: 2019
    }, {
        month_index: 5,
        amount_of_days: 30,
        starting_day: 6,
        year: 2019
    }, {
        month_index: 6,
        amount_of_days: 31,
        starting_day: 1,
        year: 2019
    }, {
        month_index: 7,
        amount_of_days: 31,
        starting_day: 4,
        year: 2019
    }, {
        month_index: 8,
        amount_of_days: 30,
        starting_day: 7,
        year: 2019
    }, {
        month_index: 9,
        amount_of_days: 31,
        starting_day: 2,
        year: 2019
    }, {
        month_index: 10,
        amount_of_days: 30,
        starting_day: 5,
        year: 2019
    }, {
        month_index: 11,
        amount_of_days: 31,
        starting_day: 0,
        year: 2019
    }, {
        month_index: 0,
        amount_of_days: 31,
        starting_day: 4,
        year: 2020
    }, {
        month_index: 1,
        amount_of_days: 28,
        starting_day: 6,
        year: 2020
    }, {
        month_index: 2,
        amount_of_days: 31,
        starting_day: 0,
        year: 2020
    }, {
        month_index: 3,
        amount_of_days: 30,
        starting_day: 3,
        year: 2020
    }, {
        month_index: 4,
        amount_of_days: 31,
        starting_day: 5,
        year: 2020
    }, {
        month_index: 5,
        amount_of_days: 30,
        starting_day: 1,
        year: 2020
    }, {
        month_index: 6,
        amount_of_days: 31,
        starting_day: 3,
        year: 2020
    }, {
        month_index: 7,
        amount_of_days: 31,
        starting_day: 6,
        year: 2020
    }, {
        month_index: 8,
        amount_of_days: 30,
        starting_day: 2,
        year: 2020
    }, {
        month_index: 9,
        amount_of_days: 31,
        starting_day: 4,
        year: 2020
    }, {
        month_index: 10,
        amount_of_days: 30,
        starting_day: 0,
        year: 2020
    }, {
        month_index: 11,
        amount_of_days: 31,
        starting_day: 2,
        year: 2020
    }, {
        month_index: 0,
        amount_of_days: 31,
        starting_day: 5,
        year: 2021
    }
];

var data = {
    current_modal_popup: 0,
    current_color: {
        color_name: "blue",
        color: "#1B19CD",
        off_color: "#7C7EFB"
    },
    current_date: {
        day: "Default",
        date: "Default",
        month: "Default",
        year: "Default"
    },
    calendar: {
        month: "Default",
        year: "Default"
    },
    post_its: {
        current_post_it_id: 0,
        current_post_it_index: 0,
        current_post_it_new: true
    }
};

